# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
np.version.version

'1.21.5'

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
np.size(a)

10

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
np.info(np.dot)

 dot()

dot(a, b, out=None)

Dot product of two arrays. Specifically,

- If both `a` and `b` are 1-D arrays, it is inner product of vectors
  (without complex conjugation).

- If both `a` and `b` are 2-D arrays, it is matrix multiplication,
  but using :func:`matmul` or ``a @ b`` is preferred.

- If either `a` or `b` is 0-D (scalar), it is equivalent to :func:`multiply`
  and using ``numpy.multiply(a, b)`` or ``a * b`` is preferred.

- If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
  the last axis of `a` and `b`.

- If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
  sum product over the last axis of `a` and the second-to-last axis of `b`::

    dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])

Parameters
----------
a : array_like
    First argument.
b : array_like
    Second argument.
out : ndarray, optional
    Output argument. This must have the exact kind that would be returned
    if it was not used. In particular, it must have the righ

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
a = np.array([1,2,0,0,4,0])
np.nonzero(a)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
np.random.random((3,3,3))

array([[[0.18161556, 0.30852015, 0.40598502],
        [0.25923348, 0.49374325, 0.28556094],
        [0.36827491, 0.88797652, 0.33609239]],

       [[0.61249597, 0.59258918, 0.9192446 ],
        [0.50738657, 0.6320021 , 0.14710926],
        [0.3751408 , 0.02945905, 0.77175817]],

       [[0.98175062, 0.15290194, 0.54425105],
        [0.65003022, 0.08553842, 0.94846303],
        [0.04737435, 0.20146154, 0.91504172]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
a = np.random.random((10, 10))
print(f'Matrix:\n{a}')
print(f'\nMin: {a.min()}, Max: {a.max()}')

Matrix:
[[0.27606348 0.68331332 0.88715156 0.60747789 0.1379246  0.08685145
  0.33822563 0.32684036 0.24452896 0.69727172]
 [0.17803158 0.59117915 0.90381888 0.93893188 0.90517873 0.68651303
  0.40065206 0.38567523 0.50835935 0.25278339]
 [0.88482323 0.59317841 0.66074099 0.62572724 0.18874658 0.45313075
  0.01731686 0.14629238 0.57016764 0.53945469]
 [0.99727832 0.9766422  0.40879928 0.31280551 0.26260883 0.47101166
  0.28896115 0.54686043 0.81810897 0.20865882]
 [0.06029894 0.30685393 0.99530802 0.02045604 0.53053883 0.37367547
  0.68062278 0.83529261 0.2147916  0.99415905]
 [0.25229577 0.41397483 0.17528003 0.92546385 0.73143414 0.07563835
  0.68489697 0.76701992 0.85632577 0.81088132]
 [0.09700612 0.26605973 0.5161203  0.7479965  0.28042765 0.30948507
  0.17244759 0.08086561 0.84198029 0.56472832]
 [0.46152407 0.53445033 0.00787145 0.05303453 0.13910182 0.01639096
  0.26993077 0.15867953 0.16037847 0.53942674]
 [0.05961026 0.57236943 0.64270512 0.14335716 0.44421605 0.64733597
  0.

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
a = np.random.random(30)
print(f'Matrix:\n{a}\n\nMean value: {a.mean()}')

Matrix:
[0.22796345 0.46021582 0.79295166 0.36487869 0.81468196 0.45199683
 0.27114006 0.64012254 0.05709    0.79225188 0.95929494 0.89570744
 0.80581364 0.02655716 0.24859999 0.48727132 0.93659188 0.13391979
 0.52548276 0.15048418 0.22165653 0.03123463 0.90953688 0.49873425
 0.43004681 0.41782493 0.88288617 0.48054679 0.76174255 0.32329273]

Mean value: 0.5000172755866246


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
a = np.ones((5,5))
a[1:-1,1:-1] = 0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
a = np.ones((3,3))
np.pad(a, pad_width=1, mode='constant', constant_values=0)

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
np.diag(1 + np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
a = np.zeros((8, 8))
a[1::2, ::2] = 1
a[::2, 1::2] = 1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [20]:
np.unravel_index(100, (6, 7, 8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [21]:
np.tile([0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0], 4).reshape(8, 8)

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [22]:
a = np.random.random((5, 5))

mean = a.mean()
std = a.std()
normalized = (a - mean) / std

print(f'Before normalization:\n{a}')
print(f'\nAfter normalization:\n{normalized}')

Before normalization:
[[0.81324957 0.71745869 0.18085023 0.42736061 0.65520725]
 [0.67212185 0.30755694 0.09821172 0.65327762 0.47056174]
 [0.89697365 0.4248088  0.71200643 0.58423584 0.59721061]
 [0.21262535 0.28656688 0.95429085 0.5101666  0.23420074]
 [0.79102843 0.8954499  0.43154199 0.04449587 0.69899151]]

After normalization:
[[ 1.10669933  0.73134578 -1.37133773 -0.40539451  0.48741546]
 [ 0.55369477 -0.87484146 -1.69515417  0.47985424 -0.23611221]
 [ 1.43476954 -0.41539367  0.70998127  0.2093162   0.26015742]
 [-1.24682794 -0.95709035  1.65936522 -0.0809218  -1.16228542]
 [ 1.01962649  1.42879878 -0.38900991 -1.90563804  0.65898271]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [23]:
np.dtype([("r", np.ubyte),
          ("g", np.ubyte),
          ("b", np.ubyte),
          ("a", np.ubyte)])

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [24]:
np.dot(np.random.random((5, 3)), np.random.random((3, 2)))

array([[0.98975543, 1.21202945],
       [0.95485405, 0.86731072],
       [1.12713319, 1.32058471],
       [0.90193452, 0.68712504],
       [0.57410221, 0.72711214]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [25]:
a = np.random.random(10) * 10
a = np.where((a > 3) & (a < 8), a * -1, a)
a

array([ 1.33574486, -4.02339365, -3.89629885,  8.65026693, -5.99612757,
       -7.18526909,  1.8352549 ,  0.87255297,  0.25163175,  0.02895128])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [26]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [27]:
Z = np.random.random((3,3))
print(Z**Z)

print(Z <- Z)
print(1j*Z)
print(Z/1/1)


[[0.97060777 0.99761273 0.69324223]
 [0.84153232 0.69771114 0.70340681]
 [0.70045577 0.69845604 0.94395522]]
[[False False False]
 [False False False]
 [False False False]]
[[0.+0.96970352j 0.+0.99760701j 0.+0.33512323j]
 [0.+0.06207436j 0.+0.29418983j 0.+0.26467483j]
 [0.+0.46514825j 0.+0.45218438j 0.+0.94051826j]]
[[0.96970352 0.99760701 0.33512323]
 [0.06207436 0.29418983 0.26467483]
 [0.46514825 0.45218438 0.94051826]]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [28]:


np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [29]:
a = np.random.uniform(-10, 10, 10)
np.copysign(np.ceil(np.abs(a)), a)

array([ -5.,  -8.,   3., -10.,  -9.,   4.,   4.,   5.,   9.,   5.])

#### 30. How to find common values between two arrays? (★☆☆)

In [30]:
np.intersect1d([0, 1, 2, 3, 4], [3, 4, 5, 6, 7])

array([3, 4])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [31]:
np.seterr(all='ignore')
'''with np.errstate(divide='warn'):
    np.arange(5) / 0.'''

"with np.errstate(divide='warn'):\n    np.arange(5) / 0."

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [32]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [33]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print("Yestraday: ", yesterday)
print("Today: ", today)
print("Tomorrow: ", tomorrow)

Yestraday:  2022-11-18
Today:  2022-11-19
Tomorrow:  2022-11-20


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [34]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [35]:
A = 1
B = 2
np.multiply((np.add(A, B, out=None)), (np.divide((np.negative(A, out=None)), 2, out=None)), out=None)

-1.5

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [36]:
a = np.random.random(10) * 10
a - a % 1, np.floor(a), a.astype(int), np.trunc(a)

(array([1., 8., 0., 0., 0., 8., 7., 2., 5., 7.]),
 array([1., 8., 0., 0., 0., 8., 7., 2., 5., 7.]),
 array([1, 8, 0, 0, 0, 8, 7, 2, 5, 7]),
 array([1., 8., 0., 0., 0., 8., 7., 2., 5., 7.]))

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [37]:
np.tile(np.arange(0, 5), 5).reshape(5, 5)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [38]:
np.fromiter(np.random.random(10) * 10, int)

array([6, 2, 1, 2, 6, 5, 2, 2, 3, 0])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [39]:
np.linspace(0, 1, 12)[1: -1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [40]:
a = np.random.random(10) * 10
print("Before sort:", a)
print("\nAfter sort :", np.sort(a))

Before sort: [5.82482675 4.92120347 1.40041564 6.59492903 9.66676174 4.30204073
 0.62070943 6.44559483 6.93903303 9.09123776]

After sort : [0.62070943 1.40041564 4.30204073 4.92120347 5.82482675 6.44559483
 6.59492903 6.93903303 9.09123776 9.66676174]


#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)